#!/bin/bash

curl https://miro.medium.com/v2/resize:fit:1400/1*CIjxfX_1Xk_ts763BA39MQ.jpeg > albatross.jpeg

aws s3 cp albatross.jpeg s3://ds2022-bqu3tr/

aws s3 presign --expires-in 604800 s3://ds2022-bqu3tr/albatross.jpeg

final_url = 'https://ds2022-bqu3tr.s3.us-east-1.amazonaws.com/albatross.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAWFIPTE7FR62UOQKE%2F20241003%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241003T141415Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=d71f1aed883559cd9bb86773a932a45808be306372a74a9bc09f1a6399ec630e'


